language: python
python:
  - "2.7"
install:
  - pip install -r requirements.txt
  - pip install -r requirements-dev.txt
script:
  # check that default CSW connections work
  - paver check_default_csw_connections
  # check that docs build and links work
  - cd docs
  - make html
  - make linkcheck
  # ensure all code is pep8 compliant
  - find plugin -type f -name "*.py" | xargs pep8
  - pep8 pavement.py
